export const biharDistricts = [
  { value: 'patna', label: 'Patna' },
  { value: 'gaya', label: 'Gaya' },
  { value: 'muzaffarpur', label: 'Muzaffarpur' },
  { value: 'darbhanga', label: 'Darbhanga' },
  { value: 'bhagalpur', label: 'Bhagalpur' },
  { value: 'saharsa', label: 'Saharsa' },
  { value: 'purnia', label: 'Purnia' },
  { value: 'katihar', label: 'Katihar' },
  { value: 'begusarai', label: 'Begusarai' },
  { value: 'samastipur', label: 'Samastipur' },
  { value: 'chapra', label: 'Chapra' },
  { value: 'sitamarhi', label: 'Sitamarhi' },
  { value: 'madhubani', label: 'Madhubani' },
  { value: 'supaul', label: 'Supaul' },
  { value: 'araria', label: 'Araria' },
  { value: 'kishanganj', label: 'Kishanganj' },
  { value: 'aurangabad', label: 'Aurangabad' },
  { value: 'jehanabad', label: 'Jehanabad' },
  { value: 'nalanda', label: 'Nalanda' },
  { value: 'nawada', label: 'Nawada' },
  { value: 'rohtas', label: 'Rohtas' },
  { value: 'buxar', label: 'Buxar' },
  { value: 'kaimur', label: 'Kaimur' },
  { value: 'gopalganj', label: 'Gopalganj' },
  { value: 'siwan', label: 'Siwan' },
  { value: 'saran', label: 'Saran' },
  { value: 'vaishali', label: 'Vaishali' },
  { value: 'east_champaran', label: 'East Champaran' },
  { value: 'west_champaran', label: 'West Champaran' },
  { value: 'sheohar', label: 'Sheohar' },
  { value: 'madhepura', label: 'Madhepura' },
  { value: 'khagaria', label: 'Khagaria' },
  { value: 'munger', label: 'Munger' },
  { value: 'lakhisarai', label: 'Lakhisarai' },
  { value: 'sheikhpura', label: 'Sheikhpura' },
  { value: 'jamui', label: 'Jamui' },
  { value: 'banka', label: 'Banka' },
  { value: 'arwal', label: 'Arwal' },
];

export const subjects = [
  { value: 'mathematics', label: 'Mathematics' },
  { value: 'science', label: 'Science' },
  { value: 'english', label: 'English' },
  { value: 'hindi', label: 'Hindi' },
  { value: 'social_science', label: 'Social Science' },
  { value: 'physics', label: 'Physics' },
  { value: 'chemistry', label: 'Chemistry' },
  { value: 'biology', label: 'Biology' },
  { value: 'history', label: 'History' },
  { value: 'geography', label: 'Geography' },
  { value: 'economics', label: 'Economics' },
  { value: 'political_science', label: 'Political Science' },
  { value: 'computer_science', label: 'Computer Science' },
  { value: 'physical_education', label: 'Physical Education' },
  { value: 'art', label: 'Art' },
  { value: 'music', label: 'Music' },
];

export const gradeLevels = [
  { value: 'primary', label: 'Primary (1-5)' },
  { value: 'middle', label: 'Middle (6-8)' },
  { value: 'high_school', label: 'High School (9-10)' },
  { value: 'senior_secondary', label: 'Senior Secondary (11-12)' },
];

export const maxDistances = [
  { value: '25', label: '25 km' },
  { value: '50', label: '50 km' },
  { value: '75', label: '75 km' },
  { value: '100', label: '100 km' },
];
